# # you're doing.
Vagrant.configure(2) do |config|
  # boxes at https://atlas.hashicorp.com/search.
config.vm.box = "Centos7"
# using a specific IP.
config.vm.network "private_network", ip: "192.168.10.13"

config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
vb.memory = "1024"
end
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
#config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get updiate
  #   sudo apt-get install -y apache2


#SHELL
   config.vm.provision "shell", path: "node3_start_script.sh"

end
