apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
    heritage: helm
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31200
    protocol: TCP

  selector:
    app: jenkins
  "type": "NodePort"
